FROM node:20.19.4-alpine3.22

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3333

CMD sh -c "npx prisma migrate deploy && npm run prisma:seed && npm run start"